before_commands:
    - composer install --dev --no-interaction
tools:
    php_sim: true
    php_analyzer:
        enabled: true
        filter:
            excluded_paths:
                - './bin/*'
                - './vendor/*'
                - './build/*'
    php_code_sniffer:
        config:
            standard: "PSR2"
        filter:
            paths:
                - './src/*'
                - './tests/*'
    php_cpd:
        enabled: true
        excluded_dirs:
            - ./bin
            - ./vendor
            - ./build
    php_pdepend:
        enabled: true
        excluded_dirs:
            - ./bin
            - ./vendor
            - ./build
    php_loc:
        enabled: true
        excluded_dirs:
            - ./bin
            - ./vendor
            - ./build
    php_mess_detector:
        enabled: true
        config:
            rulesets:
                - cleancode
                - codesize
                - unusedcode
                - naming
                - design
                - controversial
        filter:
            excluded_paths:
                - './bin/*'
                - './vendor/*'
                - './build/*'
build:
    environment:
        php: '5.6.0'
    tests:
        override:
            -
                command: './bin/phpunit -c ./phpunit.xml.dist --coverage-clover=./build/logs/clover.xml'
                coverage:
                    file: './build/logs/clover.xml'
                    format: 'php-clover'
checks:
    php:
        code_rating: true
        duplication: true
